apiVersion: v1
kind: Service
metadata:
  name: rancher-metadata-airgap
  namespace: cattle-system
spec:
  selector:
    app: rancher-metadata-airgap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
